#!/bin/bash

mkdir -p ~/.vim
mkdir -p ~/.vim/autoload
mkdir -p ~/.vim/bundle
mkdir -p ~/.vim/colors
mkdir -p ~/.vim/swap
mkdir -p ~/.mintty/themes

cp -iv ./.bashrc ~/
cp -iv ./.emacs ~/
cp -iv ./.vimrc ~/
cp -iv ./.gitconfig ~/
cp -iv ./.tmux.conf ~/
cp -iv ./mintty/themes/base16-brewer.minttyrc ~/.mintty/themes/
cp -iv ~/.vim/colors/base16-brewer.vim ~/.vim/colors/

pushd ~/.vim/autoload
curl -LO "https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim"
popd

pushd ~/.vim/bundle
git clone https://github.com/scrooloose/nerdtree
git clone https://github.com/guns/vim-clojure-static
git clone https://github.com/tpope/fireplace
git clone https://github.com/tpope/vim-sensible
popd
