#!/bin/bash

mkdir -p ~/.vim
mkdir -p ~/.vim/autoload
mkdir -p ~/.vim/bundle
mkdir -p ~/.vim/colors
mkdir -p ~/.vim/swap

cp -iv ./.bashrc ~/
cp -iv ./.emacs ~/
cp -iv ./.vimrc ~/
cp -iv ./.gitconfig ~/
cp -iv ./.vim/colors/minimalist.vim ~/.vim/colors/
cp -iv ./.vim/colors/chroma.vim ~/.vim/colors/

cd ~/.vim/autoload
curl -LO "https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim"

cd ~/.vim/bundle
git clone https://github.com/scrooloose/nerdtree
git clone https://github.com/tpope/vim-sensible
